### ISSUE TITLE
README typo! Code 3! P1! Batten down the hatches!

### ISSUE THREAD

**Issue by b-layer** [benknoble/wiki-md#6]
Hey DBK. 

Just took my first look at things. Sounds ambitious! Or not. I need to do more than read the README before coming to any firm conclusions on anything. I'm just poking my head in here. One question in my mind is how broad of a reach you want this to have and how that jibes with potential users' required level of Vim knowledge. (Maybe I'll better be able to answer that for myself with some more exploring...)

Hey, but, this is an issue report so I gotta break..er..report something so here are a couple items about the README that you are more than welcome to totally ignore...

Grammar issue ("exists for that targets") obscures the meaning of this bullet point...

> because a filetype exists for that targets all wiki entries, you can customize your experience in those files by adding to an ftplugin...

Use of "the author" is a bit formal if not awkward, IMHO. Maybe just "I"?

And to end with some PRO level nitpicking...this sentence threw me a little. "Better yet..." or "Even better..." ? 

> Better, it's only two keystrokes away.

LOL.

Though they encompass very different scopes I like how both of our READMEs have a blurb along the lines of "That's it. Simple, right? Well, not really."  :)

Will do some more exploring. Cheers.
B

**Comment by benknoble** [comment]
Thanks B; I have more feedback from Rich (vi.se chat). I may paste it here and it to the “issue.”

**Comment by benknoble** [comment]
> I don't think you've nailed the README yet: I skimmed the first 2/3
> of the README and realised I had no idea what it did. I switched my brain on and
> re-read it, but I still found I had to think in order to figure out what the
> plugin does.
> 
> FWIW, I think wiki-md-core does a good better of explaining what it does than
> the README's What does it do? section
> 
> If I were re-writing it myself, I'd probably consider starting out with the sort
> of things it allows you to do (e.g. press gf on anything to jump to it) and then
> follow up with how it works: I think that the vast majority of Vim users don't
> even know that 'path' exists, let alone know the details of what it does or how
> it works.
> 
> I like to think that I'm a reasonably experienced user of Vim but nailing down
> the detailed functionality of 'path' in my brain and configuring it correctly in
> my setup is still on my TODO list
> 
> Maybe some examples of what the mysterious autoload functions you allude to can
> do might also be helpful?
> 
> As for the plugin itself, I haven't looked into it in detail yet, but it sounds
> pretty terrific! I already have a wiki setup in Vim using a very obscure
> not-a-plugin utility (soywiki), but if I didn't, I'd definitely try yours first
>   
> ...and maybe will be compelled to switch over when I've read more of your
> plugin's :help!
> 
> Another thought:
> 
> The :help is explicit about how the new filetype works
> 
> When reading the README, again I had to think about it to figure out how it
> would work: you say that: a). there's a new filetype b). any file can be a wiki
> file c). the new filetype is added to existing filetypes...
> 
> ...but I don't think that makes it clear that when you're viewing a file that
> both of the filetypes apply
> 
> ...and if you're not already aware of Vim's support for typea.typeb filetypes, I
> think that section is pretty confusing
> 
> Again, I think the :help is much clearer
> 
> Actually... sorry, that info is included in the README... I just think that
> having it in the how to get started section leaves the what does it do section
> confusing
> 
> ...hope this is the sort of feedback you were looking for and I'm not just being
> rude...
> 
> More nit-picky: you refer to yourself both in the third person ("the author")
> and in the first person. You should probably stick to one of these styles (and
> fwiw, I prefer the first person references)
> 
> ...I think I see why you've used "the author" instead of "I" in that section,
> but I don't think it really works.
>

**Comment by benknoble** [comment]
Hey @b-layer, would really appreciate any feedback on the edits in #7 if you have some time. Your insights were really helpful, thanks!

**Comment by b-layer** [comment]
> 
> 
> Hey @b-layer, would really appreciate any feedback on the edits in #7 if you have some time. Your insights were really helpful, thanks!

Sure. I haven't had much time...musecnav has been stagnating, too...but I'll look this week.

**Comment by benknoble** [comment]
More feedback from Rich:

> There are just a few phrases that I stumbled over when reading it:
> "Ultimately, the goal is to" <- I think this is unnecessary hedging. Your plugin does do this, and this disclaimer makes it sound like that's just something that's far away on the roadmap.
> "library functions that may prove useful in crafting" <- this one is actually fine, but similar to the above, the "may" come across as a bit timid. Ideas for changes: "that you can use to craft", "that can be used to craft"
> "I find those and most other methods both disorganized and not discoverable" <- this phrase is a bit clunky. I think it's the "not discoverable" that I dislike the most.
> I think you should make "flashy popups" into a link to your code that implements a flashy popup.
> I'm loving the hubris in "It is remarkably difficult to describe something which is simultaneously the absence of so much and the power to do anything." ;)
> I don't know if the rest of the addendum is really necessary any more. In particular, this last bit seems unnecessarily modest: "I fear that a poor attempt to describe what is contained here will turn away so many who might otherwise enjoy this plugin."
> I'm not sure if this phrase works: It prefers customization over sane defaults. I hope it doesn't use bad defaults?
> Perhaps "opinionated defaults" would get your point across better?
> I think there's a more elegant way to write "attempts to enhance the experience of navigating it"

**Comment by b-layer** [comment]
Hey DBK. 

Generally, much improved. I'm a lot closer to "getting it" than I was. Right now I have just two things starting with a minor typo here:

**Ay** file with the wiki filetype will have the wiki tree added to 'path'.

And...

Having your config avaialble is a good idea. How about some comments in the code/config, though? Especially the popup handling code. Better yet, formally document that since it would be a desirable feature..."put your mappings in a data structure like this and they automatically be shown and selectable in a popup". If that's more "opinionated" then you're going for then fall back to the "add comments" suggestion.

**Comment by b-layer** [comment]
I should temper the above a tad. One thing to keep in mind is that I can now reasonably be classified as a plugin developer. Add that to my already exalted status as a Vim Ninja and, well, I know a heck of a lot about Vim. Just like you. So you should try to get some less elite eyes to take a look at this as soon as you can. (Wink emojis implied for much of this.)

**Comment by benknoble** [comment]
@b-layer Great comments; I'm working on a separate plugin to do the popups using a similar data-structure 😉 but I do agree I should find a way to explain what's going on in that config. It started as just a sort of dump, but I'll go back and add some detail.
